# Einleitung {-} 

Die enorme Verbreitung, die das Internet auch im Bildungsbereich gefunden hat, hat Studieren und Forschen heute bereits stark verändert und es in Zukunft noch viel mehr tun. Wir denken dabei noch gar nicht an die radikalen Veränderungen, die mit Schlagwörtern wie "e-Learning" oder "virtuelle Universität" beschrieben werden und sich in ihrer vollen Tragweite erst abzuzeichnen beginnen, sondern an den ganz normalen Arbeits- und Studieralltag in unseren Bildungsinstitutionen. Dieses Buch richtet sich an all jene, die in diesem Alltag stecken: Studierende, die (über Seminar- und Abschlussarbeiten) ins wissenschaftliche Arbeiten einsteigen, und Wissenschafterinnen, deren berufliche Tätigkeit sich durch das Internet stark verändert hat.

Es gibt bereits hunderte Bücher, die genau diese Veränderungen zum Thema haben und die detailliert und praxisnah beschreiben, wie man/frau sich dieser neuen Möglichkeiten bedienen kann. Diese "How-To-Do" Bücher (Wie suche ich im Internet? Wie benutze ich E-Mail möglichst effektiv? usw) behandeln aber meist nur das _Wie_ und nicht das _Warum_ und _Wozu_.So wichtig es ist, zu lernen, wie man E-Mail verschickt, bleibt doch die vorgelagerte Frage offen: Warum überhaupt E-Mail? Warum nicht zum Telefon greifen oder ein Fax schicken? Oder anders ausgedrückt: _Wann_, zu _welchem Zweck_ verwende ich _welches Werkzeug_? _Wie_ dieses Werkzeug dann zu bedienen ist, ist erst die nächste, allerdings nicht vom Zweck zu trennende Fragestellung.

Wahrscheinlich müssen sich alle Autorinnen von Praxisbüchern, die das Wort "Internet" im Titel führen, einer doppelten Herausforderung stellen: Erstens: Wie kann der relative lange Publikationszyklus eines Buches mit der raschen Entwicklung des Internets mithalten? Wie kann verhindert werden, dass nicht bereits beim Erscheinen ein wesentlicher Teil des Inhalts bereits veraltet ist? Und zweitens: Wie können Anleitungen und Tipps so gestaltet werden, dass sie einerseits nicht zu spezifisch sind, d.h. nur für eine spezielle Software, für einen speziellen Fall gelten, andererseits aber doch so konkret gehalten werden, dass sie praxisrelevant sind?

An der ersten Herausforderung wäre die Herausgabe dieses Buches fast gescheitert. Ein Buch mit dem Titel "Studieren und Forschen mit dem Internet" hatten wir bereits zweimal in der Rohfassung fertig und dann doch wieder verworfen und komplett umgeschrieben. Zwar blieben einige Grundgedanken und Abschnitte erhalten, aber die Themen und Schwerpunkte verlagerten sich ständig. Immer wieder schien es uns, dass einige Fragen inzwischen an Bedeutung gewonnen hatten und daher mehr Gewicht (Platz) erhalten sollten, während andere Abschnitte durch die neueren Entwicklungen bereits überholt wurden. 

Erst mit der Ausgliederung aller Detailinformationen, vor allem sämtlicher konkreter Hinweise und Internet-Adressen, in eine -- zum Buch gehörende -- Homepage (Website) glauben wir nun dieses Problem halbwegs gelöst zu haben. ^[Diese Website, die ein Entwicklungsprojekt des damaligen Bundesministerium war, gibt es inzwischen nicht mehr und dementsprechend habe ich auch die nächsten Absätze gestrichen…] ^[Von der Einleitung fehlt mir der Originaltext. Ich musste daher die alte Fassung händisch neu eingeben. Daher ist die Einleitung das einzige Kapitel, wo ich direkte Anmerkungen mache; alle anderen Kapitel habe ich textlich (nicht jedoch von der Form her) 1:1 übernommen.]


Nach diesem Hinweis auf die Erweiterungen des Buches sind zwei Anmerkungen notwendig darüber, was das Buch _nicht_ enthält:

1. Wir behandeln im Buch nicht alle Fachgebiete, sondern beschränken uns auf die Sozia- und Wirtschafts- und Geisteswissenschaften. Vorgangsweise und Methodik in den anderen Gebieten sind uns zu wenig vertraut, um sie voll integrieren zu können. Zumindest jene Kapitel, die grundlegende Fertigkeiten des wissenschaftlichen Arbeitens behandeln, sollten jedoch auch für die anderen Fachgebiete relevant sein.
2. Wir haben den gesamten Bereich der empirischen Arbeiten -- sowohl quantitative als auch qualitative Ansätze -- vollkommen ausgeklammert. Das wäre -- wegen der unterschiedlichen Arbeitsweise, Methodik und vor allem Möglichkeiten, die das Internet bietet, ein eigenes Buch mit mindestens demselben Umfang notwendig. ^[Das ist ein entscheidender Punkt, den ich mit dem neuen Buchprojekt -- nämlich gerade durch die Einbindung von R -- nachkommen möchte.]

Beim Bemühen um eine geschlechtsneutrale Sprache {siehe auch Kapitel \@ref(schreiben): [Schreiben]} haben wir der leichteren Lesbarkeit halber sowohl auf das sogenannte Binnen-I als auch auf die umständlichen Schrägstriche verzichtet. Statt dessen haben wir weitgehend weibliche Formen verwendet. Diese radikale Schreibweise stört nicht so sehr den Lesefluss, bringt aber doch immer das Problem der geschlechtsspezifischen Sprache ins Bewusstsein. Nur in wenigen Fällen haben wir -- ganz bewusst -- die männliche Form gewählt. Es handelt sich dann meist um Inhalte mit negativen Unterton. So ist von einem überarbeiteten, "vergesslichen" Betreuer die Rede, aber von einer Betreuerin, mit der Sie die nächsten Schritte abklären. ^[Den Rest der Einleitung habe ich in dieser Fassung ersatzlose gestrichen.]





